### ISSUE TITLE
Verification Token Appears to no longer exist at step 5

### ISSUE THREAD

**Issue by phatmandrake** [scrthq/GoogleAppsScriptSheetMQ#1]
The Verification token doesn't appear to be on the Hangouts Chat API configuration page. I can see no mention of it at: https://developers.google.com/hangouts/chat/how-tos/bots-apps-script#manifest_file

Wondering if there is another way to generate this token.

**Comment by scrthq** [comment]
@phatmandrake - Hmmmmmmm interesting! Have you tried excluding it? Curious if it's no longer a requirement for some reason

**Comment by scrthq** [comment]
It looks like Google may have adjusted their auth mechanism as they gear up to support Hangouts Chat API as a native service in Apps Script per the [Async Messages section above](https://developers.google.com/hangouts/chat/how-tos/bots-apps-script#async_messages)

Checking this out further on my end once I have a second, but PR's very welcome if you figure out what needs adjusting!

**Comment by scrthq** [comment]
Merged in! Thanks again!!
